name: user-chamomile

on:
  push:
    branches: [ "main", "develop","feature*" ]
  pull_request:
    branches: [ "main", "develop","feature*" ]
  workflow_dispatch:
    branches: [ "main", "develop","feature*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install test

    - name: Imprimir el directorio de trabajo
      run: pwd

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dotnet-sonarscanner
      run: dotnet tool install dotnet-sonarscanner --global

    - name: SonarScanner begin analysis
      run: dotnet sonarscanner begin /k:"lind-exe_Statify" /o:"lind-exe" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet build /home/runner/work/user-chamomile/user-chamomile
        dotnet test --collect "Code Coverage"

    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=MariaVasquez_user-chamomile
          -Dsonar.organization=mariavasquez
          -Dsonar.java.binaries=target/classes/
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.verbose=true
          -Dsonar.coverage.jacoco.xmlReportPaths=
              /home/runner/work/user-chamomile/user-chamomile/target/site/jacoco-aggregate/jacoco.xml
              sonar:sonar -Pcoverage
