name: user-chamomile

on:
  push:
    branches: [ "main", "develop","feature*" ]
  pull_request:
    branches: [ "main", "develop","feature*" ]
  workflow_dispatch:
    branches: [ "main", "develop","feature*" ]

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
    - name: Use variables
      run: |
        echo "datasource variable : $DATASOURCE_BD"
        echo "user variable : $USER_BD"
        echo "password variable : $PASSWORD_BD"
        echo "variable from shell environment : $env_var"
      env:
        REPOSITORY_VAR: ${{ vars.DATASOURCE_BD }}
        ORGANIZATION_VAR: ${{ vars.USER_BD }}
        OVERRIDE_VAR: ${{ vars.PASSWORD_BD }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install
      working-directory: /home/runner/work/user-chamomile/user-chamomile

    - name: Imprimir el directorio de trabajo
      run: pwd

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dotnet-sonarscanner
      run: dotnet tool install dotnet-sonarscanner --global

    - name: SonarScanner begin analysis
      run: dotnet sonarscanner begin /k:"lind-exe_Statify" /o:"lind-exe" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
 
    - name: Build and analyze with SonarCloud
      run: mvn clean verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      
