name: user-chamomile

on:
  push:
    branches: [ "main", "develop","feature*" ]
  pull_request:
    branches: [ "main", "develop","feature*" ]
  workflow_dispatch:
    branches: [ "main", "develop","feature*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
      working-directory: /home/runner/work/user-chamomile/user-chamomile

    - name: Imprimir el directorio de trabajo
      run: pwd

    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=MariaVasquez_user-chamomile
          -Dsonar.organization=mariavasquez
          -Dsonar.java.binaries=target/classes/
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.verbose=true
          -Dsonar.coverage.jacoco.xmlReportPaths=
              /home/runner/work/user-chamomile/user-chamomile/target/site/jacoco-aggregate/jacoco.xml
              sonar:sonar -Pcoverage
