name: user-chamomile

on:
  push:
    branches: [ "main", "develop","feature*" ]
  pull_request:
    branches: [ "main", "develop","feature*" ]
  workflow_dispatch:
    branches: [ "main", "develop","feature*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install test
